// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
// Version: 2022.1
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module system_top_access_memB_Pipeline_REGS_WRITEBACK (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        tmp_write_ptr_0_2_reload,
        tmp_write_ptr_1_2_reload,
        tmp_write_ptr_2_2_reload,
        tmp_write_ptr_3_2_reload,
        system_top_bool_bool_unsigned_int_unsigned_int_procVecType_const_procVe_11,
        system_top_bool_bool_unsigned_int_unsigned_int_procVecType_const_procVe_11_ap_vld,
        system_top_bool_bool_unsigned_int_unsigned_int_procVecType_const_procVe_10,
        system_top_bool_bool_unsigned_int_unsigned_int_procVecType_const_procVe_10_ap_vld,
        system_top_bool_bool_unsigned_int_unsigned_int_procVecType_const_procVe_9,
        system_top_bool_bool_unsigned_int_unsigned_int_procVecType_const_procVe_9_ap_vld,
        system_top_bool_bool_unsigned_int_unsigned_int_procVecType_const_procVe_8,
        system_top_bool_bool_unsigned_int_unsigned_int_procVecType_const_procVe_8_ap_vld
);

parameter    ap_ST_fsm_state1 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [7:0] tmp_write_ptr_0_2_reload;
input  [7:0] tmp_write_ptr_1_2_reload;
input  [7:0] tmp_write_ptr_2_2_reload;
input  [7:0] tmp_write_ptr_3_2_reload;
output  [7:0] system_top_bool_bool_unsigned_int_unsigned_int_procVecType_const_procVe_11;
output   system_top_bool_bool_unsigned_int_unsigned_int_procVecType_const_procVe_11_ap_vld;
output  [7:0] system_top_bool_bool_unsigned_int_unsigned_int_procVecType_const_procVe_10;
output   system_top_bool_bool_unsigned_int_unsigned_int_procVecType_const_procVe_10_ap_vld;
output  [7:0] system_top_bool_bool_unsigned_int_unsigned_int_procVecType_const_procVe_9;
output   system_top_bool_bool_unsigned_int_unsigned_int_procVecType_const_procVe_9_ap_vld;
output  [7:0] system_top_bool_bool_unsigned_int_unsigned_int_procVecType_const_procVe_8;
output   system_top_bool_bool_unsigned_int_unsigned_int_procVecType_const_procVe_8_ap_vld;

reg ap_idle;
reg system_top_bool_bool_unsigned_int_unsigned_int_procVecType_const_procVe_11_ap_vld;
reg system_top_bool_bool_unsigned_int_unsigned_int_procVecType_const_procVe_10_ap_vld;
reg system_top_bool_bool_unsigned_int_unsigned_int_procVecType_const_procVe_9_ap_vld;
reg system_top_bool_bool_unsigned_int_unsigned_int_procVecType_const_procVe_8_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_block_state1_pp0_stage0_iter0;
wire   [0:0] icmp_ln126_fu_86_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire   [7:0] tmp_s_fu_102_p6;
wire   [1:0] trunc_ln127_fu_98_p1;
reg   [2:0] j_fu_50;
wire   [2:0] add_ln126_fu_92_p2;
wire    ap_loop_init;
reg   [2:0] ap_sig_allocacmp_j_6;
wire   [1:0] tmp_s_fu_102_p5;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_done_reg = 1'b0;
end

system_top_mux_42_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
mux_42_8_1_1_U5430(
    .din0(tmp_write_ptr_0_2_reload),
    .din1(tmp_write_ptr_1_2_reload),
    .din2(tmp_write_ptr_2_2_reload),
    .din3(tmp_write_ptr_3_2_reload),
    .din4(tmp_s_fu_102_p5),
    .dout(tmp_s_fu_102_p6)
);

system_top_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        if ((icmp_ln126_fu_86_p2 == 1'd0)) begin
            j_fu_50 <= add_ln126_fu_92_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            j_fu_50 <= 3'd0;
        end
    end
end

always @ * begin
    if ((ap_start_int == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ * begin
    if (((icmp_ln126_fu_86_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ * begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ * begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ * begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ * begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_sig_allocacmp_j_6 = 3'd0;
    end else begin
        ap_sig_allocacmp_j_6 = j_fu_50;
    end
end

always @ * begin
    if (((trunc_ln127_fu_98_p1 == 2'd1) & (icmp_ln126_fu_86_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        system_top_bool_bool_unsigned_int_unsigned_int_procVecType_const_procVe_10_ap_vld = 1'b1;
    end else begin
        system_top_bool_bool_unsigned_int_unsigned_int_procVecType_const_procVe_10_ap_vld = 1'b0;
    end
end

always @ * begin
    if (((trunc_ln127_fu_98_p1 == 2'd0) & (icmp_ln126_fu_86_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        system_top_bool_bool_unsigned_int_unsigned_int_procVecType_const_procVe_11_ap_vld = 1'b1;
    end else begin
        system_top_bool_bool_unsigned_int_unsigned_int_procVecType_const_procVe_11_ap_vld = 1'b0;
    end
end

always @ * begin
    if (((trunc_ln127_fu_98_p1 == 2'd3) & (icmp_ln126_fu_86_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        system_top_bool_bool_unsigned_int_unsigned_int_procVecType_const_procVe_8_ap_vld = 1'b1;
    end else begin
        system_top_bool_bool_unsigned_int_unsigned_int_procVecType_const_procVe_8_ap_vld = 1'b0;
    end
end

always @ * begin
    if (((trunc_ln127_fu_98_p1 == 2'd2) & (icmp_ln126_fu_86_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        system_top_bool_bool_unsigned_int_unsigned_int_procVecType_const_procVe_9_ap_vld = 1'b1;
    end else begin
        system_top_bool_bool_unsigned_int_unsigned_int_procVecType_const_procVe_9_ap_vld = 1'b0;
    end
end

always @ * begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln126_fu_92_p2 = (ap_sig_allocacmp_j_6 + 3'd1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

always @ * begin
    ap_block_state1_pp0_stage0_iter0 = (ap_start_int == 1'b0);
end

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign icmp_ln126_fu_86_p2 = ((ap_sig_allocacmp_j_6 == 3'd4) ? 1'b1 : 1'b0);

assign system_top_bool_bool_unsigned_int_unsigned_int_procVecType_const_procVe_10 = tmp_s_fu_102_p6;

assign system_top_bool_bool_unsigned_int_unsigned_int_procVecType_const_procVe_11 = tmp_s_fu_102_p6;

assign system_top_bool_bool_unsigned_int_unsigned_int_procVecType_const_procVe_8 = tmp_s_fu_102_p6;

assign system_top_bool_bool_unsigned_int_unsigned_int_procVecType_const_procVe_9 = tmp_s_fu_102_p6;

assign tmp_s_fu_102_p5 = ap_sig_allocacmp_j_6[1:0];

assign trunc_ln127_fu_98_p1 = ap_sig_allocacmp_j_6[1:0];

endmodule //system_top_access_memB_Pipeline_REGS_WRITEBACK
