// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
// Version: 2022.1
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module system_top_crossbar_Pipeline_SERVICE_REQUEST_3 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        fwd_req_34,
        fwd_req_56,
        p_ZZ3runbPKbPbP8procUnitPKhPK8procTvecP11procVecTypePA16_6memRepP11networkUnitS5_70,
        p_ZZ3runbPKbPbP8procUnitPKhPK8procTvecP11procVecTypePA16_6memRepP11networkUnitS5_71,
        p_ZZ3runbPKbPbP8procUnitPKhPK8procTvecP11procVecTypePA16_6memRepP11networkUnitS5_72,
        p_ZZ3runbPKbPbP8procUnitPKhPK8procTvecP11procVecTypePA16_6memRepP11networkUnitS5_73,
        p_ZZ3runbPKbPbP8procUnitPKhPK8procTvecP11procVecTypePA16_6memRepP11networkUnitS5_74,
        p_ZZ3runbPKbPbP8procUnitPKhPK8procTvecP11procVecTypePA16_6memRepP11networkUnitS5_75,
        p_ZZ3runbPKbPbP8procUnitPKhPK8procTvecP11procVecTypePA16_6memRepP11networkUnitS5_76,
        p_ZZ3runbPKbPbP8procUnitPKhPK8procTvecP11procVecTypePA16_6memRepP11networkUnitS5_77,
        fwd_req_01,
        tmp54,
        cmp89,
        req_dest_pu_out,
        req_dest_pu_out_ap_vld,
        auto_req_1_out,
        auto_req_1_out_ap_vld
);

parameter    ap_ST_fsm_state1 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [7:0] fwd_req_34;
input  [0:0] fwd_req_56;
input  [7:0] p_ZZ3runbPKbPbP8procUnitPKhPK8procTvecP11procVecTypePA16_6memRepP11networkUnitS5_70;
input  [7:0] p_ZZ3runbPKbPbP8procUnitPKhPK8procTvecP11procVecTypePA16_6memRepP11networkUnitS5_71;
input  [7:0] p_ZZ3runbPKbPbP8procUnitPKhPK8procTvecP11procVecTypePA16_6memRepP11networkUnitS5_72;
input  [7:0] p_ZZ3runbPKbPbP8procUnitPKhPK8procTvecP11procVecTypePA16_6memRepP11networkUnitS5_73;
input  [7:0] p_ZZ3runbPKbPbP8procUnitPKhPK8procTvecP11procVecTypePA16_6memRepP11networkUnitS5_74;
input  [7:0] p_ZZ3runbPKbPbP8procUnitPKhPK8procTvecP11procVecTypePA16_6memRepP11networkUnitS5_75;
input  [7:0] p_ZZ3runbPKbPbP8procUnitPKhPK8procTvecP11procVecTypePA16_6memRepP11networkUnitS5_76;
input  [7:0] p_ZZ3runbPKbPbP8procUnitPKhPK8procTvecP11procVecTypePA16_6memRepP11networkUnitS5_77;
input  [7:0] fwd_req_01;
input  [0:0] tmp54;
input  [0:0] cmp89;
output  [7:0] req_dest_pu_out;
output   req_dest_pu_out_ap_vld;
output  [0:0] auto_req_1_out;
output   auto_req_1_out_ap_vld;

reg ap_idle;
reg req_dest_pu_out_ap_vld;
reg auto_req_1_out_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_block_state1_pp0_stage0_iter0;
wire   [0:0] icmp_ln228_fu_194_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg   [0:0] auto_req_reg_170;
wire   [0:0] auto_req_1_fu_301_p2;
reg   [0:0] ap_phi_mux_auto_req_phi_fu_173_p4;
wire    ap_loop_init;
reg   [7:0] req_dest_pu_fu_70;
wire   [7:0] req_dest_pu_1_fu_307_p3;
reg   [7:0] ap_sig_allocacmp_req_dest_pu_load_1;
reg   [3:0] i_5_fu_74;
wire   [3:0] add_ln228_fu_200_p2;
reg   [3:0] ap_sig_allocacmp_i;
wire   [1:0] a_fu_209_p4;
wire   [0:0] b_fu_223_p1;
wire   [7:0] tmp_s_fu_227_p4;
wire   [7:0] tmp_175_fu_237_p4;
wire   [7:0] tmp_176_fu_247_p4;
wire   [7:0] tmp_177_fu_257_p4;
wire   [1:0] tmp_178_fu_267_p5;
wire   [7:0] tmp_178_fu_267_p6;
wire   [0:0] icmp_ln232_fu_281_p2;
wire   [7:0] zext_ln229_fu_219_p1;
wire   [0:0] or_ln232_fu_295_p2;
wire   [7:0] select_ln232_fu_287_p3;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_done_reg = 1'b0;
end

system_top_mux_21_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 1 ),
    .dout_WIDTH( 8 ))
mux_21_8_1_1_U4588(
    .din0(p_ZZ3runbPKbPbP8procUnitPKhPK8procTvecP11procVecTypePA16_6memRepP11networkUnitS5_70),
    .din1(p_ZZ3runbPKbPbP8procUnitPKhPK8procTvecP11procVecTypePA16_6memRepP11networkUnitS5_71),
    .din2(b_fu_223_p1),
    .dout(tmp_s_fu_227_p4)
);

system_top_mux_21_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 1 ),
    .dout_WIDTH( 8 ))
mux_21_8_1_1_U4589(
    .din0(p_ZZ3runbPKbPbP8procUnitPKhPK8procTvecP11procVecTypePA16_6memRepP11networkUnitS5_72),
    .din1(p_ZZ3runbPKbPbP8procUnitPKhPK8procTvecP11procVecTypePA16_6memRepP11networkUnitS5_73),
    .din2(b_fu_223_p1),
    .dout(tmp_175_fu_237_p4)
);

system_top_mux_21_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 1 ),
    .dout_WIDTH( 8 ))
mux_21_8_1_1_U4590(
    .din0(p_ZZ3runbPKbPbP8procUnitPKhPK8procTvecP11procVecTypePA16_6memRepP11networkUnitS5_74),
    .din1(p_ZZ3runbPKbPbP8procUnitPKhPK8procTvecP11procVecTypePA16_6memRepP11networkUnitS5_75),
    .din2(b_fu_223_p1),
    .dout(tmp_176_fu_247_p4)
);

system_top_mux_21_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 1 ),
    .dout_WIDTH( 8 ))
mux_21_8_1_1_U4591(
    .din0(p_ZZ3runbPKbPbP8procUnitPKhPK8procTvecP11procVecTypePA16_6memRepP11networkUnitS5_76),
    .din1(p_ZZ3runbPKbPbP8procUnitPKhPK8procTvecP11procVecTypePA16_6memRepP11networkUnitS5_77),
    .din2(b_fu_223_p1),
    .dout(tmp_177_fu_257_p4)
);

system_top_mux_42_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 8 ))
mux_42_8_1_1_U4592(
    .din0(tmp_s_fu_227_p4),
    .din1(tmp_175_fu_237_p4),
    .din2(tmp_176_fu_247_p4),
    .din3(tmp_177_fu_257_p4),
    .din4(tmp_178_fu_267_p5),
    .dout(tmp_178_fu_267_p6)
);

system_top_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        if ((icmp_ln228_fu_194_p2 == 1'd0)) begin
            i_5_fu_74 <= add_ln228_fu_200_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_5_fu_74 <= 4'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        if ((icmp_ln228_fu_194_p2 == 1'd0)) begin
            req_dest_pu_fu_70 <= req_dest_pu_1_fu_307_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            req_dest_pu_fu_70 <= fwd_req_34;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln228_fu_194_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        auto_req_reg_170 <= auto_req_1_fu_301_p2;
    end
end

always @ * begin
    if ((ap_start_int == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ * begin
    if (((icmp_ln228_fu_194_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ * begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ * begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ * begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_phi_mux_auto_req_phi_fu_173_p4 = fwd_req_56;
    end else begin
        ap_phi_mux_auto_req_phi_fu_173_p4 = auto_req_reg_170;
    end
end

always @ * begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ * begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_sig_allocacmp_i = 4'd0;
    end else begin
        ap_sig_allocacmp_i = i_5_fu_74;
    end
end

always @ * begin
    if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_sig_allocacmp_req_dest_pu_load_1 = fwd_req_34;
    end else begin
        ap_sig_allocacmp_req_dest_pu_load_1 = req_dest_pu_fu_70;
    end
end

always @ * begin
    if (((icmp_ln228_fu_194_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        auto_req_1_out_ap_vld = 1'b1;
    end else begin
        auto_req_1_out_ap_vld = 1'b0;
    end
end

always @ * begin
    if (((icmp_ln228_fu_194_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        req_dest_pu_out_ap_vld = 1'b1;
    end else begin
        req_dest_pu_out_ap_vld = 1'b0;
    end
end

always @ * begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign a_fu_209_p4 = {{ap_sig_allocacmp_i[2:1]}};

assign add_ln228_fu_200_p2 = (ap_sig_allocacmp_i + 4'd1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

always @ * begin
    ap_block_state1_pp0_stage0_iter0 = (ap_start_int == 1'b0);
end

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign auto_req_1_fu_301_p2 = (or_ln232_fu_295_p2 | ap_phi_mux_auto_req_phi_fu_173_p4);

assign auto_req_1_out = ap_phi_mux_auto_req_phi_fu_173_p4;

assign b_fu_223_p1 = ap_sig_allocacmp_i[0:0];

assign icmp_ln228_fu_194_p2 = ((ap_sig_allocacmp_i == 4'd8) ? 1'b1 : 1'b0);

assign icmp_ln232_fu_281_p2 = ((tmp_178_fu_267_p6 == fwd_req_01) ? 1'b1 : 1'b0);

assign or_ln232_fu_295_p2 = (tmp54 & icmp_ln232_fu_281_p2);

assign req_dest_pu_1_fu_307_p3 = ((cmp89[0:0] == 1'b1) ? select_ln232_fu_287_p3 : ap_sig_allocacmp_req_dest_pu_load_1);

assign req_dest_pu_out = req_dest_pu_fu_70;

assign select_ln232_fu_287_p3 = ((icmp_ln232_fu_281_p2[0:0] == 1'b1) ? zext_ln229_fu_219_p1 : ap_sig_allocacmp_req_dest_pu_load_1);

assign tmp_178_fu_267_p5 = {{ap_sig_allocacmp_i[2:1]}};

assign zext_ln229_fu_219_p1 = a_fu_209_p4;

endmodule //system_top_crossbar_Pipeline_SERVICE_REQUEST_3
