// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
// Version: 2022.1
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module system_top_crossbar_Pipeline_VITIS_LOOP_243_2 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        cond131,
        trunc_ln,
        fwd_req_12,
        p_ZZ3runbPKbPbP8procUnitPKhPK8procTvecP11procVecTypePA16_6memRepP11networkUnitS5_37_i,
        p_ZZ3runbPKbPbP8procUnitPKhPK8procTvecP11procVecTypePA16_6memRepP11networkUnitS5_37_o,
        p_ZZ3runbPKbPbP8procUnitPKhPK8procTvecP11procVecTypePA16_6memRepP11networkUnitS5_37_o_ap_vld,
        p_ZZ3runbPKbPbP8procUnitPKhPK8procTvecP11procVecTypePA16_6memRepP11networkUnitS5_35_i,
        p_ZZ3runbPKbPbP8procUnitPKhPK8procTvecP11procVecTypePA16_6memRepP11networkUnitS5_35_o,
        p_ZZ3runbPKbPbP8procUnitPKhPK8procTvecP11procVecTypePA16_6memRepP11networkUnitS5_35_o_ap_vld,
        p_ZZ3runbPKbPbP8procUnitPKhPK8procTvecP11procVecTypePA16_6memRepP11networkUnitS5_33_i,
        p_ZZ3runbPKbPbP8procUnitPKhPK8procTvecP11procVecTypePA16_6memRepP11networkUnitS5_33_o,
        p_ZZ3runbPKbPbP8procUnitPKhPK8procTvecP11procVecTypePA16_6memRepP11networkUnitS5_33_o_ap_vld,
        p_ZZ3runbPKbPbP8procUnitPKhPK8procTvecP11procVecTypePA16_6memRepP11networkUnitS5_31_i,
        p_ZZ3runbPKbPbP8procUnitPKhPK8procTvecP11procVecTypePA16_6memRepP11networkUnitS5_31_o,
        p_ZZ3runbPKbPbP8procUnitPKhPK8procTvecP11procVecTypePA16_6memRepP11networkUnitS5_31_o_ap_vld,
        p_ZZ3runbPKbPbP8procUnitPKhPK8procTvecP11procVecTypePA16_6memRepP11networkUnitS5_38,
        p_ZZ3runbPKbPbP8procUnitPKhPK8procTvecP11procVecTypePA16_6memRepP11networkUnitS5_38_ap_vld,
        p_ZZ3runbPKbPbP8procUnitPKhPK8procTvecP11procVecTypePA16_6memRepP11networkUnitS5_36,
        p_ZZ3runbPKbPbP8procUnitPKhPK8procTvecP11procVecTypePA16_6memRepP11networkUnitS5_36_ap_vld,
        p_ZZ3runbPKbPbP8procUnitPKhPK8procTvecP11procVecTypePA16_6memRepP11networkUnitS5_34,
        p_ZZ3runbPKbPbP8procUnitPKhPK8procTvecP11procVecTypePA16_6memRepP11networkUnitS5_34_ap_vld,
        p_ZZ3runbPKbPbP8procUnitPKhPK8procTvecP11procVecTypePA16_6memRepP11networkUnitS5_32,
        p_ZZ3runbPKbPbP8procUnitPKhPK8procTvecP11procVecTypePA16_6memRepP11networkUnitS5_32_ap_vld
);

parameter    ap_ST_fsm_state1 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [7:0] cond131;
input  [1:0] trunc_ln;
input  [7:0] fwd_req_12;
input  [7:0] p_ZZ3runbPKbPbP8procUnitPKhPK8procTvecP11procVecTypePA16_6memRepP11networkUnitS5_37_i;
output  [7:0] p_ZZ3runbPKbPbP8procUnitPKhPK8procTvecP11procVecTypePA16_6memRepP11networkUnitS5_37_o;
output   p_ZZ3runbPKbPbP8procUnitPKhPK8procTvecP11procVecTypePA16_6memRepP11networkUnitS5_37_o_ap_vld;
input  [7:0] p_ZZ3runbPKbPbP8procUnitPKhPK8procTvecP11procVecTypePA16_6memRepP11networkUnitS5_35_i;
output  [7:0] p_ZZ3runbPKbPbP8procUnitPKhPK8procTvecP11procVecTypePA16_6memRepP11networkUnitS5_35_o;
output   p_ZZ3runbPKbPbP8procUnitPKhPK8procTvecP11procVecTypePA16_6memRepP11networkUnitS5_35_o_ap_vld;
input  [7:0] p_ZZ3runbPKbPbP8procUnitPKhPK8procTvecP11procVecTypePA16_6memRepP11networkUnitS5_33_i;
output  [7:0] p_ZZ3runbPKbPbP8procUnitPKhPK8procTvecP11procVecTypePA16_6memRepP11networkUnitS5_33_o;
output   p_ZZ3runbPKbPbP8procUnitPKhPK8procTvecP11procVecTypePA16_6memRepP11networkUnitS5_33_o_ap_vld;
input  [7:0] p_ZZ3runbPKbPbP8procUnitPKhPK8procTvecP11procVecTypePA16_6memRepP11networkUnitS5_31_i;
output  [7:0] p_ZZ3runbPKbPbP8procUnitPKhPK8procTvecP11procVecTypePA16_6memRepP11networkUnitS5_31_o;
output   p_ZZ3runbPKbPbP8procUnitPKhPK8procTvecP11procVecTypePA16_6memRepP11networkUnitS5_31_o_ap_vld;
output  [7:0] p_ZZ3runbPKbPbP8procUnitPKhPK8procTvecP11procVecTypePA16_6memRepP11networkUnitS5_38;
output   p_ZZ3runbPKbPbP8procUnitPKhPK8procTvecP11procVecTypePA16_6memRepP11networkUnitS5_38_ap_vld;
output  [7:0] p_ZZ3runbPKbPbP8procUnitPKhPK8procTvecP11procVecTypePA16_6memRepP11networkUnitS5_36;
output   p_ZZ3runbPKbPbP8procUnitPKhPK8procTvecP11procVecTypePA16_6memRepP11networkUnitS5_36_ap_vld;
output  [7:0] p_ZZ3runbPKbPbP8procUnitPKhPK8procTvecP11procVecTypePA16_6memRepP11networkUnitS5_34;
output   p_ZZ3runbPKbPbP8procUnitPKhPK8procTvecP11procVecTypePA16_6memRepP11networkUnitS5_34_ap_vld;
output  [7:0] p_ZZ3runbPKbPbP8procUnitPKhPK8procTvecP11procVecTypePA16_6memRepP11networkUnitS5_32;
output   p_ZZ3runbPKbPbP8procUnitPKhPK8procTvecP11procVecTypePA16_6memRepP11networkUnitS5_32_ap_vld;

reg ap_idle;
reg[7:0] p_ZZ3runbPKbPbP8procUnitPKhPK8procTvecP11procVecTypePA16_6memRepP11networkUnitS5_37_o;
reg p_ZZ3runbPKbPbP8procUnitPKhPK8procTvecP11procVecTypePA16_6memRepP11networkUnitS5_37_o_ap_vld;
reg[7:0] p_ZZ3runbPKbPbP8procUnitPKhPK8procTvecP11procVecTypePA16_6memRepP11networkUnitS5_35_o;
reg p_ZZ3runbPKbPbP8procUnitPKhPK8procTvecP11procVecTypePA16_6memRepP11networkUnitS5_35_o_ap_vld;
reg[7:0] p_ZZ3runbPKbPbP8procUnitPKhPK8procTvecP11procVecTypePA16_6memRepP11networkUnitS5_33_o;
reg p_ZZ3runbPKbPbP8procUnitPKhPK8procTvecP11procVecTypePA16_6memRepP11networkUnitS5_33_o_ap_vld;
reg[7:0] p_ZZ3runbPKbPbP8procUnitPKhPK8procTvecP11procVecTypePA16_6memRepP11networkUnitS5_31_o;
reg p_ZZ3runbPKbPbP8procUnitPKhPK8procTvecP11procVecTypePA16_6memRepP11networkUnitS5_31_o_ap_vld;
reg p_ZZ3runbPKbPbP8procUnitPKhPK8procTvecP11procVecTypePA16_6memRepP11networkUnitS5_38_ap_vld;
reg p_ZZ3runbPKbPbP8procUnitPKhPK8procTvecP11procVecTypePA16_6memRepP11networkUnitS5_36_ap_vld;
reg p_ZZ3runbPKbPbP8procUnitPKhPK8procTvecP11procVecTypePA16_6memRepP11networkUnitS5_34_ap_vld;
reg p_ZZ3runbPKbPbP8procUnitPKhPK8procTvecP11procVecTypePA16_6memRepP11networkUnitS5_32_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_block_state1_pp0_stage0_iter0;
wire   [0:0] icmp_ln243_fu_82_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire   [0:0] trunc_ln244_fu_94_p1;
wire   [1:0] trunc_ln_read_read_fu_62_p2;
wire   [7:0] tmp_179_fu_114_p6;
reg   [1:0] k_fu_52;
wire   [1:0] add_ln243_fu_88_p2;
wire    ap_loop_init;
reg   [1:0] ap_sig_allocacmp_k_4;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_done_reg = 1'b0;
end

system_top_mux_48_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 8 ),
    .dout_WIDTH( 8 ))
mux_48_8_1_1_U4609(
    .din0(p_ZZ3runbPKbPbP8procUnitPKhPK8procTvecP11procVecTypePA16_6memRepP11networkUnitS5_37_i),
    .din1(p_ZZ3runbPKbPbP8procUnitPKhPK8procTvecP11procVecTypePA16_6memRepP11networkUnitS5_35_i),
    .din2(p_ZZ3runbPKbPbP8procUnitPKhPK8procTvecP11procVecTypePA16_6memRepP11networkUnitS5_33_i),
    .din3(p_ZZ3runbPKbPbP8procUnitPKhPK8procTvecP11procVecTypePA16_6memRepP11networkUnitS5_31_i),
    .din4(fwd_req_12),
    .dout(tmp_179_fu_114_p6)
);

system_top_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        if ((icmp_ln243_fu_82_p2 == 1'd0)) begin
            k_fu_52 <= add_ln243_fu_88_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            k_fu_52 <= 2'd0;
        end
    end
end

always @ * begin
    if ((ap_start_int == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ * begin
    if (((icmp_ln243_fu_82_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ * begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ * begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ * begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ * begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_k_4 = 2'd0;
    end else begin
        ap_sig_allocacmp_k_4 = k_fu_52;
    end
end

always @ * begin
    if (((trunc_ln_read_read_fu_62_p2 == 2'd3) & (trunc_ln244_fu_94_p1 == 1'd1) & (icmp_ln243_fu_82_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        p_ZZ3runbPKbPbP8procUnitPKhPK8procTvecP11procVecTypePA16_6memRepP11networkUnitS5_31_o = cond131;
    end else begin
        p_ZZ3runbPKbPbP8procUnitPKhPK8procTvecP11procVecTypePA16_6memRepP11networkUnitS5_31_o = p_ZZ3runbPKbPbP8procUnitPKhPK8procTvecP11procVecTypePA16_6memRepP11networkUnitS5_31_i;
    end
end

always @ * begin
    if (((trunc_ln_read_read_fu_62_p2 == 2'd3) & (trunc_ln244_fu_94_p1 == 1'd1) & (icmp_ln243_fu_82_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        p_ZZ3runbPKbPbP8procUnitPKhPK8procTvecP11procVecTypePA16_6memRepP11networkUnitS5_31_o_ap_vld = 1'b1;
    end else begin
        p_ZZ3runbPKbPbP8procUnitPKhPK8procTvecP11procVecTypePA16_6memRepP11networkUnitS5_31_o_ap_vld = 1'b0;
    end
end

always @ * begin
    if (((trunc_ln_read_read_fu_62_p2 == 2'd3) & (trunc_ln244_fu_94_p1 == 1'd0) & (icmp_ln243_fu_82_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        p_ZZ3runbPKbPbP8procUnitPKhPK8procTvecP11procVecTypePA16_6memRepP11networkUnitS5_32_ap_vld = 1'b1;
    end else begin
        p_ZZ3runbPKbPbP8procUnitPKhPK8procTvecP11procVecTypePA16_6memRepP11networkUnitS5_32_ap_vld = 1'b0;
    end
end

always @ * begin
    if (((trunc_ln_read_read_fu_62_p2 == 2'd2) & (trunc_ln244_fu_94_p1 == 1'd1) & (icmp_ln243_fu_82_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        p_ZZ3runbPKbPbP8procUnitPKhPK8procTvecP11procVecTypePA16_6memRepP11networkUnitS5_33_o = cond131;
    end else begin
        p_ZZ3runbPKbPbP8procUnitPKhPK8procTvecP11procVecTypePA16_6memRepP11networkUnitS5_33_o = p_ZZ3runbPKbPbP8procUnitPKhPK8procTvecP11procVecTypePA16_6memRepP11networkUnitS5_33_i;
    end
end

always @ * begin
    if (((trunc_ln_read_read_fu_62_p2 == 2'd2) & (trunc_ln244_fu_94_p1 == 1'd1) & (icmp_ln243_fu_82_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        p_ZZ3runbPKbPbP8procUnitPKhPK8procTvecP11procVecTypePA16_6memRepP11networkUnitS5_33_o_ap_vld = 1'b1;
    end else begin
        p_ZZ3runbPKbPbP8procUnitPKhPK8procTvecP11procVecTypePA16_6memRepP11networkUnitS5_33_o_ap_vld = 1'b0;
    end
end

always @ * begin
    if (((trunc_ln_read_read_fu_62_p2 == 2'd2) & (trunc_ln244_fu_94_p1 == 1'd0) & (icmp_ln243_fu_82_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        p_ZZ3runbPKbPbP8procUnitPKhPK8procTvecP11procVecTypePA16_6memRepP11networkUnitS5_34_ap_vld = 1'b1;
    end else begin
        p_ZZ3runbPKbPbP8procUnitPKhPK8procTvecP11procVecTypePA16_6memRepP11networkUnitS5_34_ap_vld = 1'b0;
    end
end

always @ * begin
    if (((trunc_ln_read_read_fu_62_p2 == 2'd1) & (trunc_ln244_fu_94_p1 == 1'd1) & (icmp_ln243_fu_82_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        p_ZZ3runbPKbPbP8procUnitPKhPK8procTvecP11procVecTypePA16_6memRepP11networkUnitS5_35_o = cond131;
    end else begin
        p_ZZ3runbPKbPbP8procUnitPKhPK8procTvecP11procVecTypePA16_6memRepP11networkUnitS5_35_o = p_ZZ3runbPKbPbP8procUnitPKhPK8procTvecP11procVecTypePA16_6memRepP11networkUnitS5_35_i;
    end
end

always @ * begin
    if (((trunc_ln_read_read_fu_62_p2 == 2'd1) & (trunc_ln244_fu_94_p1 == 1'd1) & (icmp_ln243_fu_82_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        p_ZZ3runbPKbPbP8procUnitPKhPK8procTvecP11procVecTypePA16_6memRepP11networkUnitS5_35_o_ap_vld = 1'b1;
    end else begin
        p_ZZ3runbPKbPbP8procUnitPKhPK8procTvecP11procVecTypePA16_6memRepP11networkUnitS5_35_o_ap_vld = 1'b0;
    end
end

always @ * begin
    if (((trunc_ln_read_read_fu_62_p2 == 2'd1) & (trunc_ln244_fu_94_p1 == 1'd0) & (icmp_ln243_fu_82_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        p_ZZ3runbPKbPbP8procUnitPKhPK8procTvecP11procVecTypePA16_6memRepP11networkUnitS5_36_ap_vld = 1'b1;
    end else begin
        p_ZZ3runbPKbPbP8procUnitPKhPK8procTvecP11procVecTypePA16_6memRepP11networkUnitS5_36_ap_vld = 1'b0;
    end
end

always @ * begin
    if (((trunc_ln_read_read_fu_62_p2 == 2'd0) & (trunc_ln244_fu_94_p1 == 1'd1) & (icmp_ln243_fu_82_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        p_ZZ3runbPKbPbP8procUnitPKhPK8procTvecP11procVecTypePA16_6memRepP11networkUnitS5_37_o = cond131;
    end else begin
        p_ZZ3runbPKbPbP8procUnitPKhPK8procTvecP11procVecTypePA16_6memRepP11networkUnitS5_37_o = p_ZZ3runbPKbPbP8procUnitPKhPK8procTvecP11procVecTypePA16_6memRepP11networkUnitS5_37_i;
    end
end

always @ * begin
    if (((trunc_ln_read_read_fu_62_p2 == 2'd0) & (trunc_ln244_fu_94_p1 == 1'd1) & (icmp_ln243_fu_82_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        p_ZZ3runbPKbPbP8procUnitPKhPK8procTvecP11procVecTypePA16_6memRepP11networkUnitS5_37_o_ap_vld = 1'b1;
    end else begin
        p_ZZ3runbPKbPbP8procUnitPKhPK8procTvecP11procVecTypePA16_6memRepP11networkUnitS5_37_o_ap_vld = 1'b0;
    end
end

always @ * begin
    if (((trunc_ln_read_read_fu_62_p2 == 2'd0) & (trunc_ln244_fu_94_p1 == 1'd0) & (icmp_ln243_fu_82_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1) & (ap_start_int == 1'b1))) begin
        p_ZZ3runbPKbPbP8procUnitPKhPK8procTvecP11procVecTypePA16_6memRepP11networkUnitS5_38_ap_vld = 1'b1;
    end else begin
        p_ZZ3runbPKbPbP8procUnitPKhPK8procTvecP11procVecTypePA16_6memRepP11networkUnitS5_38_ap_vld = 1'b0;
    end
end

always @ * begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln243_fu_88_p2 = (ap_sig_allocacmp_k_4 + 2'd1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

always @ * begin
    ap_block_state1_pp0_stage0_iter0 = (ap_start_int == 1'b0);
end

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign icmp_ln243_fu_82_p2 = ((ap_sig_allocacmp_k_4 == 2'd2) ? 1'b1 : 1'b0);

assign p_ZZ3runbPKbPbP8procUnitPKhPK8procTvecP11procVecTypePA16_6memRepP11networkUnitS5_32 = tmp_179_fu_114_p6;

assign p_ZZ3runbPKbPbP8procUnitPKhPK8procTvecP11procVecTypePA16_6memRepP11networkUnitS5_34 = tmp_179_fu_114_p6;

assign p_ZZ3runbPKbPbP8procUnitPKhPK8procTvecP11procVecTypePA16_6memRepP11networkUnitS5_36 = tmp_179_fu_114_p6;

assign p_ZZ3runbPKbPbP8procUnitPKhPK8procTvecP11procVecTypePA16_6memRepP11networkUnitS5_38 = tmp_179_fu_114_p6;

assign trunc_ln244_fu_94_p1 = ap_sig_allocacmp_k_4[0:0];

assign trunc_ln_read_read_fu_62_p2 = trunc_ln;

endmodule //system_top_crossbar_Pipeline_VITIS_LOOP_243_2
