// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
// Version: 2022.1
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module system_top_dataflow (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        init,
        tmp_pus_done_i,
        tmp_pus_done_o,
        tmp_pus_done_o_ap_vld,
        system_top_bool_bool_unsigned_int_unsigned_int_procVecType_const_procVe_7,
        streamA_0,
        system_top_bool_bool_unsigned_int_unsigned_int_procVecType_const_procVe_15,
        system_top_bool_bool_unsigned_int_unsigned_int_procVecType_const_procVe_3_address0,
        system_top_bool_bool_unsigned_int_unsigned_int_procVecType_const_procVe_3_ce0,
        system_top_bool_bool_unsigned_int_unsigned_int_procVecType_const_procVe_3_q0,
        memReq_write_ptr_i,
        memReq_write_ptr_o,
        memReq_write_ptr_o_ap_vld,
        system_top_bool_bool_unsigned_int_unsigned_int_procVecType_const_procVe_25,
        system_top_bool_bool_unsigned_int_unsigned_int_procVecType_const_procVe_18,
        system_top_bool_bool_unsigned_int_unsigned_int_procVecType_const_procVe_17,
        system_top_bool_bool_unsigned_int_unsigned_int_procVecType_const_procVe_16,
        system_top_bool_bool_unsigned_int_unsigned_int_procVecType_const_procVe_24,
        system_top_bool_bool_unsigned_int_unsigned_int_procVecType_const_procVe_23,
        system_top_bool_bool_unsigned_int_unsigned_int_procVecType_const_procVe_22,
        system_top_bool_bool_unsigned_int_unsigned_int_procVecType_const_procVe_21,
        system_top_bool_bool_unsigned_int_unsigned_int_procVecType_const_procVe_20,
        system_top_bool_bool_unsigned_int_unsigned_int_procVecType_const_procVe_19,
        p_ZZ10system_topbRbRjS0_PK11procVecTypeS3_PS1_E15batch_row_count_10,
        p_ZZ10system_topbRbRjS0_PK11procVecTypeS3_PS1_E15batch_row_count_11,
        p_ZZ10system_topbRbRjS0_PK11procVecTypeS3_PS1_E15batch_row_count_12,
        p_ZZ10system_topbRbRjS0_PK11procVecTypeS3_PS1_E15batch_row_count_13,
        p_ZZ10system_topbRbRjS0_PK11procVecTypeS3_PS1_E15batch_row_count_14,
        p_ZZ10system_topbRbRjS0_PK11procVecTypeS3_PS1_E15batch_row_count_15,
        p_ZZ10system_topbRbRjS0_PK11procVecTypeS3_PS1_E15batch_row_count_16,
        p_ZZ10system_topbRbRjS0_PK11procVecTypeS3_PS1_E15batch_row_count_17,
        p_ZZ10system_topbRbRjS0_PK11procVecTypeS3_PS1_E15batch_row_count_18,
        p_ZZ10system_topbRbRjS0_PK11procVecTypeS3_PS1_E15batch_row_count_19,
        p_ZZ10system_topbRbRjS0_PK11procVecTypeS3_PS1_E15batch_row_count_20,
        p_ZZ10system_topbRbRjS0_PK11procVecTypeS3_PS1_E15batch_row_count_21,
        p_ZZ10system_topbRbRjS0_PK11procVecTypeS3_PS1_E15batch_row_count_22,
        p_ZZ10system_topbRbRjS0_PK11procVecTypeS3_PS1_E15batch_row_count_23,
        p_ZZ10system_topbRbRjS0_PK11procVecTypeS3_PS1_E15batch_row_count_24,
        p_ZZ10system_topbRbRjS0_PK11procVecTypeS3_PS1_E15batch_row_count_25,
        p_ZZ10system_topbRbRjS0_PK11procVecTypeS3_PS1_E15batch_row_count_26,
        p_ZZ10system_topbRbRjS0_PK11procVecTypeS3_PS1_E15batch_row_count_27,
        p_ZZ10system_topbRbRjS0_PK11procVecTypeS3_PS1_E15batch_row_count_28,
        p_ZZ10system_topbRbRjS0_PK11procVecTypeS3_PS1_E15batch_row_count_29,
        p_ZZ10system_topbRbRjS0_PK11procVecTypeS3_PS1_E15batch_row_count_30,
        p_ZZ10system_topbRbRjS0_PK11procVecTypeS3_PS1_E15batch_row_count_31,
        p_ZZ10system_topbRbRjS0_PK11procVecTypeS3_PS1_E15batch_row_count_32,
        p_ZZ10system_topbRbRjS0_PK11procVecTypeS3_PS1_E15batch_row_count_33,
        p_ZZ10system_topbRbRjS0_PK11procVecTypeS3_PS1_E15batch_row_count_34,
        p_ZZ10system_topbRbRjS0_PK11procVecTypeS3_PS1_E15batch_row_count_35,
        p_ZZ10system_topbRbRjS0_PK11procVecTypeS3_PS1_E15batch_row_count_36,
        p_ZZ10system_topbRbRjS0_PK11procVecTypeS3_PS1_E15batch_row_count_37,
        p_ZZ10system_topbRbRjS0_PK11procVecTypeS3_PS1_E15batch_row_count_38,
        p_ZZ10system_topbRbRjS0_PK11procVecTypeS3_PS1_E15batch_row_count_39,
        p_ZZ10system_topbRbRjS0_PK11procVecTypeS3_PS1_E15batch_row_count_40,
        reqMemB_address0,
        reqMemB_ce0,
        reqMemB_we0,
        reqMemB_d0,
        system_top_bool_bool_unsigned_int_unsigned_int_procVecType_const_procVe_6,
        streamA_1,
        system_top_bool_bool_unsigned_int_unsigned_int_procVecType_const_procVe_14,
        system_top_bool_bool_unsigned_int_unsigned_int_procVecType_const_procVe_2_address0,
        system_top_bool_bool_unsigned_int_unsigned_int_procVecType_const_procVe_2_ce0,
        system_top_bool_bool_unsigned_int_unsigned_int_procVecType_const_procVe_2_q0,
        system_top_bool_bool_unsigned_int_unsigned_int_procVecType_const_procVe_5,
        streamA_2,
        system_top_bool_bool_unsigned_int_unsigned_int_procVecType_const_procVe_13,
        system_top_bool_bool_unsigned_int_unsigned_int_procVecType_const_procVe_1_address0,
        system_top_bool_bool_unsigned_int_unsigned_int_procVecType_const_procVe_1_ce0,
        system_top_bool_bool_unsigned_int_unsigned_int_procVecType_const_procVe_1_q0,
        system_top_bool_bool_unsigned_int_unsigned_int_procVecType_const_procVe_4,
        streamA_3,
        system_top_bool_bool_unsigned_int_unsigned_int_procVecType_const_procVe_12,
        system_top_bool_bool_unsigned_int_unsigned_int_procVecType_const_procVe_address0,
        system_top_bool_bool_unsigned_int_unsigned_int_procVecType_const_procVe_ce0,
        system_top_bool_bool_unsigned_int_unsigned_int_procVecType_const_procVe_q0,
        comp_output_0_i,
        comp_output_0_o,
        comp_output_0_o_ap_vld,
        comp_output_1_i,
        comp_output_1_o,
        comp_output_1_o_ap_vld,
        comp_output_2_i,
        comp_output_2_o,
        comp_output_2_o_ap_vld,
        comp_output_3_i,
        comp_output_3_o,
        comp_output_3_o_ap_vld
);

parameter    ap_ST_fsm_state1 = 3'd1;
parameter    ap_ST_fsm_state2 = 3'd2;
parameter    ap_ST_fsm_state3 = 3'd4;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [0:0] init;
input  [7:0] tmp_pus_done_i;
output  [7:0] tmp_pus_done_o;
output   tmp_pus_done_o_ap_vld;
input  [0:0] system_top_bool_bool_unsigned_int_unsigned_int_procVecType_const_procVe_7;
input  [737:0] streamA_0;
input  [7:0] system_top_bool_bool_unsigned_int_unsigned_int_procVecType_const_procVe_15;
output  [3:0] system_top_bool_bool_unsigned_int_unsigned_int_procVecType_const_procVe_3_address0;
output   system_top_bool_bool_unsigned_int_unsigned_int_procVecType_const_procVe_3_ce0;
input  [751:0] system_top_bool_bool_unsigned_int_unsigned_int_procVecType_const_procVe_3_q0;
input  [7:0] memReq_write_ptr_i;
output  [7:0] memReq_write_ptr_o;
output   memReq_write_ptr_o_ap_vld;
input  [7:0] system_top_bool_bool_unsigned_int_unsigned_int_procVecType_const_procVe_25;
input  [7:0] system_top_bool_bool_unsigned_int_unsigned_int_procVecType_const_procVe_18;
input  [7:0] system_top_bool_bool_unsigned_int_unsigned_int_procVecType_const_procVe_17;
input  [7:0] system_top_bool_bool_unsigned_int_unsigned_int_procVecType_const_procVe_16;
input  [7:0] system_top_bool_bool_unsigned_int_unsigned_int_procVecType_const_procVe_24;
input  [7:0] system_top_bool_bool_unsigned_int_unsigned_int_procVecType_const_procVe_23;
input  [7:0] system_top_bool_bool_unsigned_int_unsigned_int_procVecType_const_procVe_22;
input  [7:0] system_top_bool_bool_unsigned_int_unsigned_int_procVecType_const_procVe_21;
input  [7:0] system_top_bool_bool_unsigned_int_unsigned_int_procVecType_const_procVe_20;
input  [7:0] system_top_bool_bool_unsigned_int_unsigned_int_procVecType_const_procVe_19;
input  [7:0] p_ZZ10system_topbRbRjS0_PK11procVecTypeS3_PS1_E15batch_row_count_10;
input  [7:0] p_ZZ10system_topbRbRjS0_PK11procVecTypeS3_PS1_E15batch_row_count_11;
input  [7:0] p_ZZ10system_topbRbRjS0_PK11procVecTypeS3_PS1_E15batch_row_count_12;
input  [7:0] p_ZZ10system_topbRbRjS0_PK11procVecTypeS3_PS1_E15batch_row_count_13;
input  [7:0] p_ZZ10system_topbRbRjS0_PK11procVecTypeS3_PS1_E15batch_row_count_14;
input  [7:0] p_ZZ10system_topbRbRjS0_PK11procVecTypeS3_PS1_E15batch_row_count_15;
input  [7:0] p_ZZ10system_topbRbRjS0_PK11procVecTypeS3_PS1_E15batch_row_count_16;
input  [7:0] p_ZZ10system_topbRbRjS0_PK11procVecTypeS3_PS1_E15batch_row_count_17;
input  [7:0] p_ZZ10system_topbRbRjS0_PK11procVecTypeS3_PS1_E15batch_row_count_18;
input  [7:0] p_ZZ10system_topbRbRjS0_PK11procVecTypeS3_PS1_E15batch_row_count_19;
input  [7:0] p_ZZ10system_topbRbRjS0_PK11procVecTypeS3_PS1_E15batch_row_count_20;
input  [7:0] p_ZZ10system_topbRbRjS0_PK11procVecTypeS3_PS1_E15batch_row_count_21;
input  [7:0] p_ZZ10system_topbRbRjS0_PK11procVecTypeS3_PS1_E15batch_row_count_22;
input  [7:0] p_ZZ10system_topbRbRjS0_PK11procVecTypeS3_PS1_E15batch_row_count_23;
input  [7:0] p_ZZ10system_topbRbRjS0_PK11procVecTypeS3_PS1_E15batch_row_count_24;
input  [7:0] p_ZZ10system_topbRbRjS0_PK11procVecTypeS3_PS1_E15batch_row_count_25;
input  [7:0] p_ZZ10system_topbRbRjS0_PK11procVecTypeS3_PS1_E15batch_row_count_26;
input  [7:0] p_ZZ10system_topbRbRjS0_PK11procVecTypeS3_PS1_E15batch_row_count_27;
input  [7:0] p_ZZ10system_topbRbRjS0_PK11procVecTypeS3_PS1_E15batch_row_count_28;
input  [7:0] p_ZZ10system_topbRbRjS0_PK11procVecTypeS3_PS1_E15batch_row_count_29;
input  [7:0] p_ZZ10system_topbRbRjS0_PK11procVecTypeS3_PS1_E15batch_row_count_30;
input  [7:0] p_ZZ10system_topbRbRjS0_PK11procVecTypeS3_PS1_E15batch_row_count_31;
input  [7:0] p_ZZ10system_topbRbRjS0_PK11procVecTypeS3_PS1_E15batch_row_count_32;
input  [7:0] p_ZZ10system_topbRbRjS0_PK11procVecTypeS3_PS1_E15batch_row_count_33;
input  [7:0] p_ZZ10system_topbRbRjS0_PK11procVecTypeS3_PS1_E15batch_row_count_34;
input  [7:0] p_ZZ10system_topbRbRjS0_PK11procVecTypeS3_PS1_E15batch_row_count_35;
input  [7:0] p_ZZ10system_topbRbRjS0_PK11procVecTypeS3_PS1_E15batch_row_count_36;
input  [7:0] p_ZZ10system_topbRbRjS0_PK11procVecTypeS3_PS1_E15batch_row_count_37;
input  [7:0] p_ZZ10system_topbRbRjS0_PK11procVecTypeS3_PS1_E15batch_row_count_38;
input  [7:0] p_ZZ10system_topbRbRjS0_PK11procVecTypeS3_PS1_E15batch_row_count_39;
input  [7:0] p_ZZ10system_topbRbRjS0_PK11procVecTypeS3_PS1_E15batch_row_count_40;
output  [3:0] reqMemB_address0;
output   reqMemB_ce0;
output   reqMemB_we0;
output  [40:0] reqMemB_d0;
input  [0:0] system_top_bool_bool_unsigned_int_unsigned_int_procVecType_const_procVe_6;
input  [737:0] streamA_1;
input  [7:0] system_top_bool_bool_unsigned_int_unsigned_int_procVecType_const_procVe_14;
output  [3:0] system_top_bool_bool_unsigned_int_unsigned_int_procVecType_const_procVe_2_address0;
output   system_top_bool_bool_unsigned_int_unsigned_int_procVecType_const_procVe_2_ce0;
input  [751:0] system_top_bool_bool_unsigned_int_unsigned_int_procVecType_const_procVe_2_q0;
input  [0:0] system_top_bool_bool_unsigned_int_unsigned_int_procVecType_const_procVe_5;
input  [737:0] streamA_2;
input  [7:0] system_top_bool_bool_unsigned_int_unsigned_int_procVecType_const_procVe_13;
output  [3:0] system_top_bool_bool_unsigned_int_unsigned_int_procVecType_const_procVe_1_address0;
output   system_top_bool_bool_unsigned_int_unsigned_int_procVecType_const_procVe_1_ce0;
input  [751:0] system_top_bool_bool_unsigned_int_unsigned_int_procVecType_const_procVe_1_q0;
input  [0:0] system_top_bool_bool_unsigned_int_unsigned_int_procVecType_const_procVe_4;
input  [737:0] streamA_3;
input  [7:0] system_top_bool_bool_unsigned_int_unsigned_int_procVecType_const_procVe_12;
output  [3:0] system_top_bool_bool_unsigned_int_unsigned_int_procVecType_const_procVe_address0;
output   system_top_bool_bool_unsigned_int_unsigned_int_procVecType_const_procVe_ce0;
input  [751:0] system_top_bool_bool_unsigned_int_unsigned_int_procVecType_const_procVe_q0;
input  [719:0] comp_output_0_i;
output  [719:0] comp_output_0_o;
output   comp_output_0_o_ap_vld;
input  [719:0] comp_output_1_i;
output  [719:0] comp_output_1_o;
output   comp_output_1_o_ap_vld;
input  [719:0] comp_output_2_i;
output  [719:0] comp_output_2_o;
output   comp_output_2_o_ap_vld;
input  [719:0] comp_output_3_i;
output  [719:0] comp_output_3_o;
output   comp_output_3_o_ap_vld;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[7:0] tmp_pus_done_o;
reg tmp_pus_done_o_ap_vld;
reg[7:0] memReq_write_ptr_o;
reg[719:0] comp_output_0_o;
reg[719:0] comp_output_1_o;
reg[719:0] comp_output_2_o;
reg[719:0] comp_output_3_o;

(* fsm_encoding = "none" *) reg   [2:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [0:0] result_ready_0_reg_4731;
wire    ap_CS_fsm_state2;
reg   [0:0] result_ready_1_reg_4736;
reg   [0:0] result_ready_2_reg_4741;
reg   [0:0] result_ready_3_reg_4746;
wire    grp_run_fu_2350_ap_start;
wire    grp_run_fu_2350_ap_done;
wire    grp_run_fu_2350_ap_idle;
wire    grp_run_fu_2350_ap_ready;
wire   [3:0] grp_run_fu_2350_system_top_bool_bool_unsigned_int_unsigned_int_procVecType_const_procVe_3_address0;
wire    grp_run_fu_2350_system_top_bool_bool_unsigned_int_unsigned_int_procVecType_const_procVe_3_ce0;
wire   [7:0] grp_run_fu_2350_memReq_write_ptr_o;
wire    grp_run_fu_2350_memReq_write_ptr_o_ap_vld;
wire   [3:0] grp_run_fu_2350_reqMemB_address0;
wire    grp_run_fu_2350_reqMemB_ce0;
wire    grp_run_fu_2350_reqMemB_we0;
wire   [40:0] grp_run_fu_2350_reqMemB_d0;
wire   [3:0] grp_run_fu_2350_system_top_bool_bool_unsigned_int_unsigned_int_procVecType_const_procVe_2_address0;
wire    grp_run_fu_2350_system_top_bool_bool_unsigned_int_unsigned_int_procVecType_const_procVe_2_ce0;
wire   [3:0] grp_run_fu_2350_system_top_bool_bool_unsigned_int_unsigned_int_procVecType_const_procVe_1_address0;
wire    grp_run_fu_2350_system_top_bool_bool_unsigned_int_unsigned_int_procVecType_const_procVe_1_ce0;
wire   [3:0] grp_run_fu_2350_system_top_bool_bool_unsigned_int_unsigned_int_procVecType_const_procVe_address0;
wire    grp_run_fu_2350_system_top_bool_bool_unsigned_int_unsigned_int_procVecType_const_procVe_ce0;
wire   [719:0] grp_run_fu_2350_comp_output_0_o;
wire    grp_run_fu_2350_comp_output_0_o_ap_vld;
wire   [719:0] grp_run_fu_2350_comp_output_1_o;
wire    grp_run_fu_2350_comp_output_1_o_ap_vld;
wire   [719:0] grp_run_fu_2350_comp_output_2_o;
wire    grp_run_fu_2350_comp_output_2_o_ap_vld;
wire   [719:0] grp_run_fu_2350_comp_output_3_o;
wire    grp_run_fu_2350_comp_output_3_o_ap_vld;
wire   [0:0] grp_run_fu_2350_ap_return_0;
wire   [0:0] grp_run_fu_2350_ap_return_1;
wire   [0:0] grp_run_fu_2350_ap_return_2;
wire   [0:0] grp_run_fu_2350_ap_return_3;
wire    tmp_result_1_check_pus_done_fu_4690_ap_ready;
wire   [7:0] tmp_result_1_check_pus_done_fu_4690_ap_return;
reg    grp_run_fu_2350_ap_start_reg;
wire    ap_CS_fsm_state3;
reg   [2:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 3'd1;
#0 grp_run_fu_2350_ap_start_reg = 1'b0;
end

system_top_run grp_run_fu_2350(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_run_fu_2350_ap_start),
    .ap_done(grp_run_fu_2350_ap_done),
    .ap_idle(grp_run_fu_2350_ap_idle),
    .ap_ready(grp_run_fu_2350_ap_ready),
    .init(init),
    .system_top_bool_bool_unsigned_int_unsigned_int_procVecType_const_procVe_7(system_top_bool_bool_unsigned_int_unsigned_int_procVecType_const_procVe_7),
    .streamA_0(streamA_0),
    .system_top_bool_bool_unsigned_int_unsigned_int_procVecType_const_procVe_15(system_top_bool_bool_unsigned_int_unsigned_int_procVecType_const_procVe_15),
    .system_top_bool_bool_unsigned_int_unsigned_int_procVecType_const_procVe_3_address0(grp_run_fu_2350_system_top_bool_bool_unsigned_int_unsigned_int_procVecType_const_procVe_3_address0),
    .system_top_bool_bool_unsigned_int_unsigned_int_procVecType_const_procVe_3_ce0(grp_run_fu_2350_system_top_bool_bool_unsigned_int_unsigned_int_procVecType_const_procVe_3_ce0),
    .system_top_bool_bool_unsigned_int_unsigned_int_procVecType_const_procVe_3_q0(system_top_bool_bool_unsigned_int_unsigned_int_procVecType_const_procVe_3_q0),
    .memReq_write_ptr_i(memReq_write_ptr_i),
    .memReq_write_ptr_o(grp_run_fu_2350_memReq_write_ptr_o),
    .memReq_write_ptr_o_ap_vld(grp_run_fu_2350_memReq_write_ptr_o_ap_vld),
    .system_top_bool_bool_unsigned_int_unsigned_int_procVecType_const_procVe_25(system_top_bool_bool_unsigned_int_unsigned_int_procVecType_const_procVe_25),
    .system_top_bool_bool_unsigned_int_unsigned_int_procVecType_const_procVe_18(system_top_bool_bool_unsigned_int_unsigned_int_procVecType_const_procVe_18),
    .system_top_bool_bool_unsigned_int_unsigned_int_procVecType_const_procVe_17(system_top_bool_bool_unsigned_int_unsigned_int_procVecType_const_procVe_17),
    .system_top_bool_bool_unsigned_int_unsigned_int_procVecType_const_procVe_16(system_top_bool_bool_unsigned_int_unsigned_int_procVecType_const_procVe_16),
    .system_top_bool_bool_unsigned_int_unsigned_int_procVecType_const_procVe_24(system_top_bool_bool_unsigned_int_unsigned_int_procVecType_const_procVe_24),
    .system_top_bool_bool_unsigned_int_unsigned_int_procVecType_const_procVe_23(system_top_bool_bool_unsigned_int_unsigned_int_procVecType_const_procVe_23),
    .system_top_bool_bool_unsigned_int_unsigned_int_procVecType_const_procVe_22(system_top_bool_bool_unsigned_int_unsigned_int_procVecType_const_procVe_22),
    .system_top_bool_bool_unsigned_int_unsigned_int_procVecType_const_procVe_21(system_top_bool_bool_unsigned_int_unsigned_int_procVecType_const_procVe_21),
    .system_top_bool_bool_unsigned_int_unsigned_int_procVecType_const_procVe_20(system_top_bool_bool_unsigned_int_unsigned_int_procVecType_const_procVe_20),
    .system_top_bool_bool_unsigned_int_unsigned_int_procVecType_const_procVe_19(system_top_bool_bool_unsigned_int_unsigned_int_procVecType_const_procVe_19),
    .p_ZZ10system_topbRbRjS0_PK11procVecTypeS3_PS1_E15batch_row_count_10(p_ZZ10system_topbRbRjS0_PK11procVecTypeS3_PS1_E15batch_row_count_10),
    .p_ZZ10system_topbRbRjS0_PK11procVecTypeS3_PS1_E15batch_row_count_11(p_ZZ10system_topbRbRjS0_PK11procVecTypeS3_PS1_E15batch_row_count_11),
    .p_ZZ10system_topbRbRjS0_PK11procVecTypeS3_PS1_E15batch_row_count_12(p_ZZ10system_topbRbRjS0_PK11procVecTypeS3_PS1_E15batch_row_count_12),
    .p_ZZ10system_topbRbRjS0_PK11procVecTypeS3_PS1_E15batch_row_count_13(p_ZZ10system_topbRbRjS0_PK11procVecTypeS3_PS1_E15batch_row_count_13),
    .p_ZZ10system_topbRbRjS0_PK11procVecTypeS3_PS1_E15batch_row_count_14(p_ZZ10system_topbRbRjS0_PK11procVecTypeS3_PS1_E15batch_row_count_14),
    .p_ZZ10system_topbRbRjS0_PK11procVecTypeS3_PS1_E15batch_row_count_15(p_ZZ10system_topbRbRjS0_PK11procVecTypeS3_PS1_E15batch_row_count_15),
    .p_ZZ10system_topbRbRjS0_PK11procVecTypeS3_PS1_E15batch_row_count_16(p_ZZ10system_topbRbRjS0_PK11procVecTypeS3_PS1_E15batch_row_count_16),
    .p_ZZ10system_topbRbRjS0_PK11procVecTypeS3_PS1_E15batch_row_count_17(p_ZZ10system_topbRbRjS0_PK11procVecTypeS3_PS1_E15batch_row_count_17),
    .p_ZZ10system_topbRbRjS0_PK11procVecTypeS3_PS1_E15batch_row_count_18(p_ZZ10system_topbRbRjS0_PK11procVecTypeS3_PS1_E15batch_row_count_18),
    .p_ZZ10system_topbRbRjS0_PK11procVecTypeS3_PS1_E15batch_row_count_19(p_ZZ10system_topbRbRjS0_PK11procVecTypeS3_PS1_E15batch_row_count_19),
    .p_ZZ10system_topbRbRjS0_PK11procVecTypeS3_PS1_E15batch_row_count_20(p_ZZ10system_topbRbRjS0_PK11procVecTypeS3_PS1_E15batch_row_count_20),
    .p_ZZ10system_topbRbRjS0_PK11procVecTypeS3_PS1_E15batch_row_count_21(p_ZZ10system_topbRbRjS0_PK11procVecTypeS3_PS1_E15batch_row_count_21),
    .p_ZZ10system_topbRbRjS0_PK11procVecTypeS3_PS1_E15batch_row_count_22(p_ZZ10system_topbRbRjS0_PK11procVecTypeS3_PS1_E15batch_row_count_22),
    .p_ZZ10system_topbRbRjS0_PK11procVecTypeS3_PS1_E15batch_row_count_23(p_ZZ10system_topbRbRjS0_PK11procVecTypeS3_PS1_E15batch_row_count_23),
    .p_ZZ10system_topbRbRjS0_PK11procVecTypeS3_PS1_E15batch_row_count_24(p_ZZ10system_topbRbRjS0_PK11procVecTypeS3_PS1_E15batch_row_count_24),
    .p_ZZ10system_topbRbRjS0_PK11procVecTypeS3_PS1_E15batch_row_count_25(p_ZZ10system_topbRbRjS0_PK11procVecTypeS3_PS1_E15batch_row_count_25),
    .p_ZZ10system_topbRbRjS0_PK11procVecTypeS3_PS1_E15batch_row_count_26(p_ZZ10system_topbRbRjS0_PK11procVecTypeS3_PS1_E15batch_row_count_26),
    .p_ZZ10system_topbRbRjS0_PK11procVecTypeS3_PS1_E15batch_row_count_27(p_ZZ10system_topbRbRjS0_PK11procVecTypeS3_PS1_E15batch_row_count_27),
    .p_ZZ10system_topbRbRjS0_PK11procVecTypeS3_PS1_E15batch_row_count_28(p_ZZ10system_topbRbRjS0_PK11procVecTypeS3_PS1_E15batch_row_count_28),
    .p_ZZ10system_topbRbRjS0_PK11procVecTypeS3_PS1_E15batch_row_count_29(p_ZZ10system_topbRbRjS0_PK11procVecTypeS3_PS1_E15batch_row_count_29),
    .p_ZZ10system_topbRbRjS0_PK11procVecTypeS3_PS1_E15batch_row_count_30(p_ZZ10system_topbRbRjS0_PK11procVecTypeS3_PS1_E15batch_row_count_30),
    .p_ZZ10system_topbRbRjS0_PK11procVecTypeS3_PS1_E15batch_row_count_31(p_ZZ10system_topbRbRjS0_PK11procVecTypeS3_PS1_E15batch_row_count_31),
    .p_ZZ10system_topbRbRjS0_PK11procVecTypeS3_PS1_E15batch_row_count_32(p_ZZ10system_topbRbRjS0_PK11procVecTypeS3_PS1_E15batch_row_count_32),
    .p_ZZ10system_topbRbRjS0_PK11procVecTypeS3_PS1_E15batch_row_count_33(p_ZZ10system_topbRbRjS0_PK11procVecTypeS3_PS1_E15batch_row_count_33),
    .p_ZZ10system_topbRbRjS0_PK11procVecTypeS3_PS1_E15batch_row_count_34(p_ZZ10system_topbRbRjS0_PK11procVecTypeS3_PS1_E15batch_row_count_34),
    .p_ZZ10system_topbRbRjS0_PK11procVecTypeS3_PS1_E15batch_row_count_35(p_ZZ10system_topbRbRjS0_PK11procVecTypeS3_PS1_E15batch_row_count_35),
    .p_ZZ10system_topbRbRjS0_PK11procVecTypeS3_PS1_E15batch_row_count_36(p_ZZ10system_topbRbRjS0_PK11procVecTypeS3_PS1_E15batch_row_count_36),
    .p_ZZ10system_topbRbRjS0_PK11procVecTypeS3_PS1_E15batch_row_count_37(p_ZZ10system_topbRbRjS0_PK11procVecTypeS3_PS1_E15batch_row_count_37),
    .p_ZZ10system_topbRbRjS0_PK11procVecTypeS3_PS1_E15batch_row_count_38(p_ZZ10system_topbRbRjS0_PK11procVecTypeS3_PS1_E15batch_row_count_38),
    .p_ZZ10system_topbRbRjS0_PK11procVecTypeS3_PS1_E15batch_row_count_39(p_ZZ10system_topbRbRjS0_PK11procVecTypeS3_PS1_E15batch_row_count_39),
    .p_ZZ10system_topbRbRjS0_PK11procVecTypeS3_PS1_E15batch_row_count_40(p_ZZ10system_topbRbRjS0_PK11procVecTypeS3_PS1_E15batch_row_count_40),
    .reqMemB_address0(grp_run_fu_2350_reqMemB_address0),
    .reqMemB_ce0(grp_run_fu_2350_reqMemB_ce0),
    .reqMemB_we0(grp_run_fu_2350_reqMemB_we0),
    .reqMemB_d0(grp_run_fu_2350_reqMemB_d0),
    .system_top_bool_bool_unsigned_int_unsigned_int_procVecType_const_procVe_6(system_top_bool_bool_unsigned_int_unsigned_int_procVecType_const_procVe_6),
    .streamA_1(streamA_1),
    .system_top_bool_bool_unsigned_int_unsigned_int_procVecType_const_procVe_14(system_top_bool_bool_unsigned_int_unsigned_int_procVecType_const_procVe_14),
    .system_top_bool_bool_unsigned_int_unsigned_int_procVecType_const_procVe_2_address0(grp_run_fu_2350_system_top_bool_bool_unsigned_int_unsigned_int_procVecType_const_procVe_2_address0),
    .system_top_bool_bool_unsigned_int_unsigned_int_procVecType_const_procVe_2_ce0(grp_run_fu_2350_system_top_bool_bool_unsigned_int_unsigned_int_procVecType_const_procVe_2_ce0),
    .system_top_bool_bool_unsigned_int_unsigned_int_procVecType_const_procVe_2_q0(system_top_bool_bool_unsigned_int_unsigned_int_procVecType_const_procVe_2_q0),
    .system_top_bool_bool_unsigned_int_unsigned_int_procVecType_const_procVe_5(system_top_bool_bool_unsigned_int_unsigned_int_procVecType_const_procVe_5),
    .streamA_2(streamA_2),
    .system_top_bool_bool_unsigned_int_unsigned_int_procVecType_const_procVe_13(system_top_bool_bool_unsigned_int_unsigned_int_procVecType_const_procVe_13),
    .system_top_bool_bool_unsigned_int_unsigned_int_procVecType_const_procVe_1_address0(grp_run_fu_2350_system_top_bool_bool_unsigned_int_unsigned_int_procVecType_const_procVe_1_address0),
    .system_top_bool_bool_unsigned_int_unsigned_int_procVecType_const_procVe_1_ce0(grp_run_fu_2350_system_top_bool_bool_unsigned_int_unsigned_int_procVecType_const_procVe_1_ce0),
    .system_top_bool_bool_unsigned_int_unsigned_int_procVecType_const_procVe_1_q0(system_top_bool_bool_unsigned_int_unsigned_int_procVecType_const_procVe_1_q0),
    .system_top_bool_bool_unsigned_int_unsigned_int_procVecType_const_procVe_4(system_top_bool_bool_unsigned_int_unsigned_int_procVecType_const_procVe_4),
    .streamA_3(streamA_3),
    .system_top_bool_bool_unsigned_int_unsigned_int_procVecType_const_procVe_12(system_top_bool_bool_unsigned_int_unsigned_int_procVecType_const_procVe_12),
    .system_top_bool_bool_unsigned_int_unsigned_int_procVecType_const_procVe_address0(grp_run_fu_2350_system_top_bool_bool_unsigned_int_unsigned_int_procVecType_const_procVe_address0),
    .system_top_bool_bool_unsigned_int_unsigned_int_procVecType_const_procVe_ce0(grp_run_fu_2350_system_top_bool_bool_unsigned_int_unsigned_int_procVecType_const_procVe_ce0),
    .system_top_bool_bool_unsigned_int_unsigned_int_procVecType_const_procVe_q0(system_top_bool_bool_unsigned_int_unsigned_int_procVecType_const_procVe_q0),
    .comp_output_0_i(comp_output_0_i),
    .comp_output_0_o(grp_run_fu_2350_comp_output_0_o),
    .comp_output_0_o_ap_vld(grp_run_fu_2350_comp_output_0_o_ap_vld),
    .comp_output_1_i(comp_output_1_i),
    .comp_output_1_o(grp_run_fu_2350_comp_output_1_o),
    .comp_output_1_o_ap_vld(grp_run_fu_2350_comp_output_1_o_ap_vld),
    .comp_output_2_i(comp_output_2_i),
    .comp_output_2_o(grp_run_fu_2350_comp_output_2_o),
    .comp_output_2_o_ap_vld(grp_run_fu_2350_comp_output_2_o_ap_vld),
    .comp_output_3_i(comp_output_3_i),
    .comp_output_3_o(grp_run_fu_2350_comp_output_3_o),
    .comp_output_3_o_ap_vld(grp_run_fu_2350_comp_output_3_o_ap_vld),
    .ap_return_0(grp_run_fu_2350_ap_return_0),
    .ap_return_1(grp_run_fu_2350_ap_return_1),
    .ap_return_2(grp_run_fu_2350_ap_return_2),
    .ap_return_3(grp_run_fu_2350_ap_return_3)
);

system_top_check_pus_done tmp_result_1_check_pus_done_fu_4690(
    .ap_ready(tmp_result_1_check_pus_done_fu_4690_ap_ready),
    .p_read(result_ready_0_reg_4731),
    .p_read1(result_ready_1_reg_4736),
    .p_read2(result_ready_2_reg_4741),
    .p_read3(result_ready_3_reg_4746),
    .tmp_pus_done_read(tmp_pus_done_i),
    .ap_return(tmp_result_1_check_pus_done_fu_4690_ap_return)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_run_fu_2350_ap_start_reg <= 1'b0;
    end else begin
        if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            grp_run_fu_2350_ap_start_reg <= 1'b1;
        end else if ((grp_run_fu_2350_ap_ready == 1'b1)) begin
            grp_run_fu_2350_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        result_ready_0_reg_4731 <= grp_run_fu_2350_ap_return_0;
        result_ready_1_reg_4736 <= grp_run_fu_2350_ap_return_1;
        result_ready_2_reg_4741 <= grp_run_fu_2350_ap_return_2;
        result_ready_3_reg_4746 <= grp_run_fu_2350_ap_return_3;
    end
end

always @ * begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ * begin
    if ((grp_run_fu_2350_ap_done == 1'b0)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

assign ap_ST_fsm_state3_blk = 1'b0;

always @ * begin
    if (((1'b1 == ap_CS_fsm_state3) | ((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ * begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ * begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ * begin
    if (((grp_run_fu_2350_comp_output_0_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        comp_output_0_o = grp_run_fu_2350_comp_output_0_o;
    end else begin
        comp_output_0_o = comp_output_0_i;
    end
end

always @ * begin
    if (((grp_run_fu_2350_comp_output_1_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        comp_output_1_o = grp_run_fu_2350_comp_output_1_o;
    end else begin
        comp_output_1_o = comp_output_1_i;
    end
end

always @ * begin
    if (((grp_run_fu_2350_comp_output_2_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        comp_output_2_o = grp_run_fu_2350_comp_output_2_o;
    end else begin
        comp_output_2_o = comp_output_2_i;
    end
end

always @ * begin
    if (((grp_run_fu_2350_comp_output_3_o_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state2))) begin
        comp_output_3_o = grp_run_fu_2350_comp_output_3_o;
    end else begin
        comp_output_3_o = comp_output_3_i;
    end
end

always @ * begin
    if (((1'b1 == ap_CS_fsm_state2) & (grp_run_fu_2350_memReq_write_ptr_o_ap_vld == 1'b1))) begin
        memReq_write_ptr_o = grp_run_fu_2350_memReq_write_ptr_o;
    end else begin
        memReq_write_ptr_o = memReq_write_ptr_i;
    end
end

always @ * begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        tmp_pus_done_o = tmp_result_1_check_pus_done_fu_4690_ap_return;
    end else begin
        tmp_pus_done_o = tmp_pus_done_i;
    end
end

always @ * begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        tmp_pus_done_o_ap_vld = 1'b1;
    end else begin
        tmp_pus_done_o_ap_vld = 1'b0;
    end
end

always @ * begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((ap_start == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b1 == ap_CS_fsm_state2) & (grp_run_fu_2350_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign comp_output_0_o_ap_vld = grp_run_fu_2350_comp_output_0_o_ap_vld;

assign comp_output_1_o_ap_vld = grp_run_fu_2350_comp_output_1_o_ap_vld;

assign comp_output_2_o_ap_vld = grp_run_fu_2350_comp_output_2_o_ap_vld;

assign comp_output_3_o_ap_vld = grp_run_fu_2350_comp_output_3_o_ap_vld;

assign grp_run_fu_2350_ap_start = grp_run_fu_2350_ap_start_reg;

assign memReq_write_ptr_o_ap_vld = grp_run_fu_2350_memReq_write_ptr_o_ap_vld;

assign reqMemB_address0 = grp_run_fu_2350_reqMemB_address0;

assign reqMemB_ce0 = grp_run_fu_2350_reqMemB_ce0;

assign reqMemB_d0 = grp_run_fu_2350_reqMemB_d0;

assign reqMemB_we0 = grp_run_fu_2350_reqMemB_we0;

assign system_top_bool_bool_unsigned_int_unsigned_int_procVecType_const_procVe_1_address0 = grp_run_fu_2350_system_top_bool_bool_unsigned_int_unsigned_int_procVecType_const_procVe_1_address0;

assign system_top_bool_bool_unsigned_int_unsigned_int_procVecType_const_procVe_1_ce0 = grp_run_fu_2350_system_top_bool_bool_unsigned_int_unsigned_int_procVecType_const_procVe_1_ce0;

assign system_top_bool_bool_unsigned_int_unsigned_int_procVecType_const_procVe_2_address0 = grp_run_fu_2350_system_top_bool_bool_unsigned_int_unsigned_int_procVecType_const_procVe_2_address0;

assign system_top_bool_bool_unsigned_int_unsigned_int_procVecType_const_procVe_2_ce0 = grp_run_fu_2350_system_top_bool_bool_unsigned_int_unsigned_int_procVecType_const_procVe_2_ce0;

assign system_top_bool_bool_unsigned_int_unsigned_int_procVecType_const_procVe_3_address0 = grp_run_fu_2350_system_top_bool_bool_unsigned_int_unsigned_int_procVecType_const_procVe_3_address0;

assign system_top_bool_bool_unsigned_int_unsigned_int_procVecType_const_procVe_3_ce0 = grp_run_fu_2350_system_top_bool_bool_unsigned_int_unsigned_int_procVecType_const_procVe_3_ce0;

assign system_top_bool_bool_unsigned_int_unsigned_int_procVecType_const_procVe_address0 = grp_run_fu_2350_system_top_bool_bool_unsigned_int_unsigned_int_procVecType_const_procVe_address0;

assign system_top_bool_bool_unsigned_int_unsigned_int_procVecType_const_procVe_ce0 = grp_run_fu_2350_system_top_bool_bool_unsigned_int_unsigned_int_procVecType_const_procVe_ce0;

endmodule //system_top_dataflow
