// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.1 (64-bit)
// Version: 2022.1
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module system_top_system_top_Pipeline_REP_DELAY_LOOP1 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        system_top_bool_bool_unsigned_int_unsigned_int_procVecType_const_procVe_26,
        system_top_bool_bool_unsigned_int_unsigned_int_procVecType_const_procVe_27,
        system_top_bool_bool_unsigned_int_unsigned_int_procVecType_const_procVe_28,
        system_top_bool_bool_unsigned_int_unsigned_int_procVecType_const_procVe_29,
        initialize_load,
        system_top_bool_bool_unsigned_int_unsigned_int_procVecType_const_procVe_15,
        system_top_bool_bool_unsigned_int_unsigned_int_procVecType_const_procVe_15_ap_vld,
        system_top_bool_bool_unsigned_int_unsigned_int_procVecType_const_procVe_14,
        system_top_bool_bool_unsigned_int_unsigned_int_procVecType_const_procVe_14_ap_vld,
        system_top_bool_bool_unsigned_int_unsigned_int_procVecType_const_procVe_13,
        system_top_bool_bool_unsigned_int_unsigned_int_procVecType_const_procVe_13_ap_vld,
        system_top_bool_bool_unsigned_int_unsigned_int_procVecType_const_procVe_12,
        system_top_bool_bool_unsigned_int_unsigned_int_procVecType_const_procVe_12_ap_vld
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [7:0] system_top_bool_bool_unsigned_int_unsigned_int_procVecType_const_procVe_26;
input  [7:0] system_top_bool_bool_unsigned_int_unsigned_int_procVecType_const_procVe_27;
input  [7:0] system_top_bool_bool_unsigned_int_unsigned_int_procVecType_const_procVe_28;
input  [7:0] system_top_bool_bool_unsigned_int_unsigned_int_procVecType_const_procVe_29;
input  [0:0] initialize_load;
output  [7:0] system_top_bool_bool_unsigned_int_unsigned_int_procVecType_const_procVe_15;
output   system_top_bool_bool_unsigned_int_unsigned_int_procVecType_const_procVe_15_ap_vld;
output  [7:0] system_top_bool_bool_unsigned_int_unsigned_int_procVecType_const_procVe_14;
output   system_top_bool_bool_unsigned_int_unsigned_int_procVecType_const_procVe_14_ap_vld;
output  [7:0] system_top_bool_bool_unsigned_int_unsigned_int_procVecType_const_procVe_13;
output   system_top_bool_bool_unsigned_int_unsigned_int_procVecType_const_procVe_13_ap_vld;
output  [7:0] system_top_bool_bool_unsigned_int_unsigned_int_procVecType_const_procVe_12;
output   system_top_bool_bool_unsigned_int_unsigned_int_procVecType_const_procVe_12_ap_vld;

reg ap_idle;
reg system_top_bool_bool_unsigned_int_unsigned_int_procVecType_const_procVe_15_ap_vld;
reg system_top_bool_bool_unsigned_int_unsigned_int_procVecType_const_procVe_14_ap_vld;
reg system_top_bool_bool_unsigned_int_unsigned_int_procVecType_const_procVe_13_ap_vld;
reg system_top_bool_bool_unsigned_int_unsigned_int_procVecType_const_procVe_12_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln37_fu_130_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg   [7:0] sim_rep_delay_bool_unsigned_char_const_unsigned_char_rep_delay;
reg   [7:0] sim_rep_delay_bool_unsigned_char_const_unsigned_char_rep_delay_0;
reg   [7:0] sim_rep_delay_bool_unsigned_char_const_unsigned_char_rep_delay_1_0;
reg   [7:0] sim_rep_delay_bool_unsigned_char_const_unsigned_char_rep_delay_2_0;
reg   [7:0] sim_rep_delay_bool_unsigned_char_const_unsigned_char_rep_delay_3_0;
reg   [7:0] sim_rep_delay_bool_unsigned_char_const_unsigned_char_rep_delay_1;
reg   [7:0] sim_rep_delay_bool_unsigned_char_const_unsigned_char_rep_delay_1_3;
reg   [7:0] sim_rep_delay_bool_unsigned_char_const_unsigned_char_rep_delay_2_3;
reg   [7:0] sim_rep_delay_bool_unsigned_char_const_unsigned_char_rep_delay_3_3;
reg   [7:0] sim_rep_delay_bool_unsigned_char_const_unsigned_char_rep_delay_2;
reg   [7:0] sim_rep_delay_bool_unsigned_char_const_unsigned_char_rep_delay_1_2;
reg   [7:0] sim_rep_delay_bool_unsigned_char_const_unsigned_char_rep_delay_2_2;
reg   [7:0] sim_rep_delay_bool_unsigned_char_const_unsigned_char_rep_delay_3_2;
reg   [7:0] sim_rep_delay_bool_unsigned_char_const_unsigned_char_rep_delay_1_1;
reg   [7:0] sim_rep_delay_bool_unsigned_char_const_unsigned_char_rep_delay_2_1;
reg   [7:0] sim_rep_delay_bool_unsigned_char_const_unsigned_char_rep_delay_3_1;
reg   [2:0] i_4_reg_446;
wire    ap_block_pp0_stage0_11001;
wire   [1:0] trunc_ln39_fu_142_p1;
reg   [1:0] trunc_ln39_reg_454;
wire   [7:0] select_ln298_3_fu_346_p3;
wire    ap_block_pp0_stage0;
wire   [7:0] tmp_2_fu_399_p6;
wire   [7:0] select_ln298_fu_176_p3;
wire   [7:0] select_ln298_2_fu_300_p3;
wire   [7:0] select_ln298_1_fu_238_p3;
reg   [2:0] i_fu_88;
wire   [2:0] add_ln37_fu_136_p2;
wire    ap_loop_init;
reg   [2:0] ap_sig_allocacmp_i_4;
wire   [7:0] tmp_1_fu_162_p6;
wire   [7:0] tmp_1_1_fu_224_p6;
wire   [7:0] tmp_1_2_fu_286_p6;
wire   [7:0] tmp_fu_332_p6;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 sim_rep_delay_bool_unsigned_char_const_unsigned_char_rep_delay = 8'd0;
#0 sim_rep_delay_bool_unsigned_char_const_unsigned_char_rep_delay_0 = 8'd0;
#0 sim_rep_delay_bool_unsigned_char_const_unsigned_char_rep_delay_1_0 = 8'd0;
#0 sim_rep_delay_bool_unsigned_char_const_unsigned_char_rep_delay_2_0 = 8'd0;
#0 sim_rep_delay_bool_unsigned_char_const_unsigned_char_rep_delay_3_0 = 8'd0;
#0 sim_rep_delay_bool_unsigned_char_const_unsigned_char_rep_delay_1 = 8'd0;
#0 sim_rep_delay_bool_unsigned_char_const_unsigned_char_rep_delay_1_3 = 8'd0;
#0 sim_rep_delay_bool_unsigned_char_const_unsigned_char_rep_delay_2_3 = 8'd0;
#0 sim_rep_delay_bool_unsigned_char_const_unsigned_char_rep_delay_3_3 = 8'd0;
#0 sim_rep_delay_bool_unsigned_char_const_unsigned_char_rep_delay_2 = 8'd0;
#0 sim_rep_delay_bool_unsigned_char_const_unsigned_char_rep_delay_1_2 = 8'd0;
#0 sim_rep_delay_bool_unsigned_char_const_unsigned_char_rep_delay_2_2 = 8'd0;
#0 sim_rep_delay_bool_unsigned_char_const_unsigned_char_rep_delay_3_2 = 8'd0;
#0 sim_rep_delay_bool_unsigned_char_const_unsigned_char_rep_delay_1_1 = 8'd0;
#0 sim_rep_delay_bool_unsigned_char_const_unsigned_char_rep_delay_2_1 = 8'd0;
#0 sim_rep_delay_bool_unsigned_char_const_unsigned_char_rep_delay_3_1 = 8'd0;
#0 ap_done_reg = 1'b0;
end

system_top_mux_43_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 3 ),
    .dout_WIDTH( 8 ))
mux_43_8_1_1_U5491(
    .din0(sim_rep_delay_bool_unsigned_char_const_unsigned_char_rep_delay_2),
    .din1(sim_rep_delay_bool_unsigned_char_const_unsigned_char_rep_delay_1_1),
    .din2(sim_rep_delay_bool_unsigned_char_const_unsigned_char_rep_delay_2_1),
    .din3(sim_rep_delay_bool_unsigned_char_const_unsigned_char_rep_delay_3_1),
    .din4(ap_sig_allocacmp_i_4),
    .dout(tmp_1_fu_162_p6)
);

system_top_mux_43_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 3 ),
    .dout_WIDTH( 8 ))
mux_43_8_1_1_U5492(
    .din0(sim_rep_delay_bool_unsigned_char_const_unsigned_char_rep_delay_1),
    .din1(sim_rep_delay_bool_unsigned_char_const_unsigned_char_rep_delay_1_2),
    .din2(sim_rep_delay_bool_unsigned_char_const_unsigned_char_rep_delay_2_2),
    .din3(sim_rep_delay_bool_unsigned_char_const_unsigned_char_rep_delay_3_2),
    .din4(ap_sig_allocacmp_i_4),
    .dout(tmp_1_1_fu_224_p6)
);

system_top_mux_43_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 3 ),
    .dout_WIDTH( 8 ))
mux_43_8_1_1_U5493(
    .din0(sim_rep_delay_bool_unsigned_char_const_unsigned_char_rep_delay),
    .din1(sim_rep_delay_bool_unsigned_char_const_unsigned_char_rep_delay_1_3),
    .din2(sim_rep_delay_bool_unsigned_char_const_unsigned_char_rep_delay_2_3),
    .din3(sim_rep_delay_bool_unsigned_char_const_unsigned_char_rep_delay_3_3),
    .din4(ap_sig_allocacmp_i_4),
    .dout(tmp_1_2_fu_286_p6)
);

system_top_mux_43_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 3 ),
    .dout_WIDTH( 8 ))
mux_43_8_1_1_U5494(
    .din0(system_top_bool_bool_unsigned_int_unsigned_int_procVecType_const_procVe_26),
    .din1(system_top_bool_bool_unsigned_int_unsigned_int_procVecType_const_procVe_27),
    .din2(system_top_bool_bool_unsigned_int_unsigned_int_procVecType_const_procVe_28),
    .din3(system_top_bool_bool_unsigned_int_unsigned_int_procVecType_const_procVe_29),
    .din4(ap_sig_allocacmp_i_4),
    .dout(tmp_fu_332_p6)
);

system_top_mux_43_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 8 ),
    .din3_WIDTH( 8 ),
    .din4_WIDTH( 3 ),
    .dout_WIDTH( 8 ))
mux_43_8_1_1_U5495(
    .din0(sim_rep_delay_bool_unsigned_char_const_unsigned_char_rep_delay_0),
    .din1(sim_rep_delay_bool_unsigned_char_const_unsigned_char_rep_delay_1_0),
    .din2(sim_rep_delay_bool_unsigned_char_const_unsigned_char_rep_delay_2_0),
    .din3(sim_rep_delay_bool_unsigned_char_const_unsigned_char_rep_delay_3_0),
    .din4(i_4_reg_446),
    .dout(tmp_2_fu_399_p6)
);

system_top_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln37_fu_130_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            i_fu_88 <= add_ln37_fu_136_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_88 <= 3'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        i_4_reg_446 <= ap_sig_allocacmp_i_4;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln39_fu_142_p1 == 2'd0) & (icmp_ln37_fu_130_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        sim_rep_delay_bool_unsigned_char_const_unsigned_char_rep_delay <= select_ln298_3_fu_346_p3;
        sim_rep_delay_bool_unsigned_char_const_unsigned_char_rep_delay_0 <= select_ln298_fu_176_p3;
        sim_rep_delay_bool_unsigned_char_const_unsigned_char_rep_delay_1 <= select_ln298_2_fu_300_p3;
        sim_rep_delay_bool_unsigned_char_const_unsigned_char_rep_delay_2 <= select_ln298_1_fu_238_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln39_fu_142_p1 == 2'd1) & (icmp_ln37_fu_130_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        sim_rep_delay_bool_unsigned_char_const_unsigned_char_rep_delay_1_0 <= select_ln298_fu_176_p3;
        sim_rep_delay_bool_unsigned_char_const_unsigned_char_rep_delay_1_1 <= select_ln298_1_fu_238_p3;
        sim_rep_delay_bool_unsigned_char_const_unsigned_char_rep_delay_1_2 <= select_ln298_2_fu_300_p3;
        sim_rep_delay_bool_unsigned_char_const_unsigned_char_rep_delay_1_3 <= select_ln298_3_fu_346_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln39_fu_142_p1 == 2'd2) & (icmp_ln37_fu_130_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        sim_rep_delay_bool_unsigned_char_const_unsigned_char_rep_delay_2_0 <= select_ln298_fu_176_p3;
        sim_rep_delay_bool_unsigned_char_const_unsigned_char_rep_delay_2_1 <= select_ln298_1_fu_238_p3;
        sim_rep_delay_bool_unsigned_char_const_unsigned_char_rep_delay_2_2 <= select_ln298_2_fu_300_p3;
        sim_rep_delay_bool_unsigned_char_const_unsigned_char_rep_delay_2_3 <= select_ln298_3_fu_346_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((trunc_ln39_fu_142_p1 == 2'd3) & (icmp_ln37_fu_130_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        sim_rep_delay_bool_unsigned_char_const_unsigned_char_rep_delay_3_0 <= select_ln298_fu_176_p3;
        sim_rep_delay_bool_unsigned_char_const_unsigned_char_rep_delay_3_1 <= select_ln298_1_fu_238_p3;
        sim_rep_delay_bool_unsigned_char_const_unsigned_char_rep_delay_3_2 <= select_ln298_2_fu_300_p3;
        sim_rep_delay_bool_unsigned_char_const_unsigned_char_rep_delay_3_3 <= select_ln298_3_fu_346_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln37_fu_130_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        trunc_ln39_reg_454 <= trunc_ln39_fu_142_p1;
    end
end

always @ * begin
    if (((icmp_ln37_fu_130_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ * begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ * begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ * begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ * begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ * begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_i_4 = 3'd0;
    end else begin
        ap_sig_allocacmp_i_4 = i_fu_88;
    end
end

always @ * begin
    if (((trunc_ln39_reg_454 == 2'd3) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        system_top_bool_bool_unsigned_int_unsigned_int_procVecType_const_procVe_12_ap_vld = 1'b1;
    end else begin
        system_top_bool_bool_unsigned_int_unsigned_int_procVecType_const_procVe_12_ap_vld = 1'b0;
    end
end

always @ * begin
    if (((trunc_ln39_reg_454 == 2'd2) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        system_top_bool_bool_unsigned_int_unsigned_int_procVecType_const_procVe_13_ap_vld = 1'b1;
    end else begin
        system_top_bool_bool_unsigned_int_unsigned_int_procVecType_const_procVe_13_ap_vld = 1'b0;
    end
end

always @ * begin
    if (((trunc_ln39_reg_454 == 2'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        system_top_bool_bool_unsigned_int_unsigned_int_procVecType_const_procVe_14_ap_vld = 1'b1;
    end else begin
        system_top_bool_bool_unsigned_int_unsigned_int_procVecType_const_procVe_14_ap_vld = 1'b0;
    end
end

always @ * begin
    if (((trunc_ln39_reg_454 == 2'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        system_top_bool_bool_unsigned_int_unsigned_int_procVecType_const_procVe_15_ap_vld = 1'b1;
    end else begin
        system_top_bool_bool_unsigned_int_unsigned_int_procVecType_const_procVe_15_ap_vld = 1'b0;
    end
end

always @ * begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln37_fu_136_p2 = (ap_sig_allocacmp_i_4 + 3'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign icmp_ln37_fu_130_p2 = ((ap_sig_allocacmp_i_4 == 3'd4) ? 1'b1 : 1'b0);

assign select_ln298_1_fu_238_p3 = ((initialize_load[0:0] == 1'b1) ? 8'd0 : tmp_1_1_fu_224_p6);

assign select_ln298_2_fu_300_p3 = ((initialize_load[0:0] == 1'b1) ? 8'd0 : tmp_1_2_fu_286_p6);

assign select_ln298_3_fu_346_p3 = ((initialize_load[0:0] == 1'b1) ? 8'd0 : tmp_fu_332_p6);

assign select_ln298_fu_176_p3 = ((initialize_load[0:0] == 1'b1) ? 8'd0 : tmp_1_fu_162_p6);

assign system_top_bool_bool_unsigned_int_unsigned_int_procVecType_const_procVe_12 = tmp_2_fu_399_p6;

assign system_top_bool_bool_unsigned_int_unsigned_int_procVecType_const_procVe_13 = tmp_2_fu_399_p6;

assign system_top_bool_bool_unsigned_int_unsigned_int_procVecType_const_procVe_14 = tmp_2_fu_399_p6;

assign system_top_bool_bool_unsigned_int_unsigned_int_procVecType_const_procVe_15 = tmp_2_fu_399_p6;

assign trunc_ln39_fu_142_p1 = ap_sig_allocacmp_i_4[1:0];

endmodule //system_top_system_top_Pipeline_REP_DELAY_LOOP1
